# Generated by Django 5.1.4 on 2024-12-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_content', models.TextField(max_length=1000)),
                ('blog_author', models.CharField(max_length=15)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_date', models.DateField(auto_now=True)),
                ('created_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Blog_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sub_blog_images/')),
                ('content', models.TextField(max_length=1000)),
                ('fk_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_blog_images', to='admin_app.blog')),
            ],
        ),
    ]
