# Generated by Django 5.1.4 on 2024-12-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('product_brand', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(max_length=6)),
                ('product_specifications', models.TextField(max_length=1000)),
                ('product_highlights', models.TextField(max_length=1000)),
                ('product_category', models.CharField(choices=[('men_shoes', 'Men Shoes'), ('women_shoes', 'Women Shoes'), ('kids', 'Kids')], default='men_shoes', max_length=20)),
            ],
        ),
    ]
