# Generated by Django 5.1.4 on 2025-01-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_blog_image',
            name='name',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
