# Generated by Django 5.1.4 on 2025-01-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('admin_contact_enquiry', 'admin_contact_enquiry'), ('admin_order', 'admin_order'), ('user_cart', 'user_cart'), ('user_order', 'user_order')], max_length=50, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
